### ISSUE TITLE
Wrong size for localized buttons

### ISSUE THREAD

**Issue by glixx** [iTALC/italc#11]
There is bug with size (width) for localized buttons. See screenshot with bug in attachment.
![italc](https://cloud.githubusercontent.com/assets/2681872/13228275/264f1d46-d9ac-11e5-9ac6-2a0ce13003ce.png)

How to fix:
- wrap text on 2 strings instead of 1
or
- calculate localized width correct

**Comment by barteekelder** [comment]
Hi,
How did you activate an other language on iTALC? Because I have tried serveral languages now but nothing works for me, and I would like to have dutch on iTALC.

I'm sorry but I do not know how to deal with your problem though, maybe you can lookup the code of your language and change something there.

**Comment by glixx** [comment]
No dutch translation for italc.
LC_ALL=uk italc
LC_ALL=ru italc
