### ISSUE TITLE
[feature] Links into text messages

### ISSUE THREAD

**Issue by nailyk-fr** [iTALC/italc#81]
`Before starting the implementation of a new feature, please always file an issue for your idea and suggestions about your feature and about the intended implementation on GitHub and wait for replies! There may be different ideas, improvements, hints or maybe an already ongoing work on this feature.`

Hi, 
We are planning a test session into my school with your software. However some functionalities are missing for us. The biggest one is about text messaging: 
- there is no way to copy/paste message, 
- links are not usable. 

I would like to work on this (quickly as test begin on next Tuesday) then submit a PR. 

Are you ok with this? 

If yes, can you, please, 
- provide me build instruction for windows? 
- entry point into the code where the text message is displayed into the client computer. 

Thanks in advance.

**Comment by tobydox** [comment]
I'm currently completely rewriting most parts of iTALC so I'd recommend to wait at least a few weeks until stabilization phase begins. Otherwise your changes will work in iTALC 3 only and need to be implemented again for iTALC 4.

Concerning the required features some questions for better understanding: is it about text messages on student computers? Do you want links inside the message boxes to be clickable and/or selectable (+copyable)? It shouldn't be hard to implement and I'd even offer to do that once iTALC 4 is in shape.

Besides I'm sorry to say that there are no build instructions for Windows. You can cross-compile iTALC for Windows on Linux, see the documentation directory. Alternatively you can try to open the project in Qt Creator on Windows and install all the required libraries into the MinGW toolchain.

**Comment by nailyk-fr** [comment]
Thanks for your quick answer. 

Yes features I would like to add are exactly what you describes: 
teacher paste a link into text messaging, 
student receive message as a popup and can click on the link (extra: is copyable)
link is opened with default browser. 

I'm mostly using linux so cross-compiling shouldn't be that hard. 

P.S.: will leave the issue open a few to attach a PR if I'm able to.

**Comment by nailyk-fr** [comment]
Thanks for merging.
